export enum ErrorCode {
  // Docker 相关
  DOCKER_NOT_AVAILABLE = 'DOCKER_NOT_AVAILABLE',
  DOCKER_PERMISSION_DENIED = 'DOCKER_PERMISSION_DENIED',

  // 凭证相关
  CREDENTIALS_NOT_FOUND = 'CREDENTIALS_NOT_FOUND',
  CREDENTIALS_INVALID = 'CREDENTIALS_INVALID',

  // 容器相关
  CONTAINER_START_FAILED = 'CONTAINER_START_FAILED',
  IMAGE_PULL_FAILED = 'IMAGE_PULL_FAILED',

  // 文件系统相关
  WORKSPACE_NOT_WRITABLE = 'WORKSPACE_NOT_WRITABLE',
  DISK_SPACE_INSUFFICIENT = 'DISK_SPACE_INSUFFICIENT',
  VERSE_FILE_CORRUPTED = 'VERSE_FILE_CORRUPTED',

  // 通用错误
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
